
path: C:/STUDIA/VI_SEM/PIT/ApplikacjaSamochodowa/training
train: images/train
val: check/images

names:
  0: car
  1: number_plate
  2: A
  3: B
  4: C
  5: D
  6: E
  7: F
  8: G
  9: H
  10: I
  11: J
  12: K
  13: L
  14: M
  15: N
  16: O
  17: P
  18: Q
  19: R
  20: S
  21: T
  22: U
  23: V
  24: W
  25: X
  26: Y
  27: Z
  28: 1
  29: 2
  30: 3
  31: 4
  32: 5
  33: 6
  34: 7
  35: 8
  36: 9
  37: 0